apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-green
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      lables:
        type: webserver
        color: green
    spec:
      nodeselector:
